### ISSUE TITLE
can you add a default conf.ini to the pip package 

### ISSUE THREAD

**Issue by pinikomarov** [zahlabut/LogTool#2]
This is so we don't have to recreate and maintain a conf.ini file in  tobiko , just tweak the changes we need.

so the flow would be we install logtool via pip , then we take the conf file with it and change just the log file names

the default conf ini can be a copy of : 
 LogTool/LogTool_Package/conf.ini 

So that if there's anything to fix there you can do it and maintain versions of it with each pip release
Sounds ok  ?

**Comment by zahlabut** [comment]
Hi Pini!

If you don't provide .ini file in your code, conf.ini is used by default
then. Not good?

**Comment by pinikomarov** [comment]
sounds ok
